POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "Develop",
  "content": "Java&Kotlin"
}

###
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "Sport",
  "content": "Brazilian jiu-jitsu"
}

###
POST http://localhost:8080/api/v1/posts
Content-Type: application/json

{
  "title": "Music",
  "content": "Romantic"
}

###